### ISSUE TITLE
Proposal Generator Bash

### ISSUE THREAD

**Issue by Bhaney44** [ChoiceCoin/Voting#1092]
Details
===================
First Prize: 50,000.00 Choice | Silver Badge
Second Prize: 12,000.00 Choice | Bronze Badge
Third Prize: 7,000.00 Choice | Bronze Badge
Deadline: December 31, 7:00PM PT

Goal
===================
The goal for this Bash is to create a way for anyone to make a proposal to be voted on in a DAO. To enter this task, developers should construct a mechanism for generating new proposals and allowing users to make new proposals. The task is open ended to allow creativity, but the following criteria and functional requirements are intended to provide guidance.

Criteria
====================
1. The program must be submitted as a pull request in the `Proposal_Processor` [folder](https://github.com/Bhaney44/Voting/tree/main/Proposal_Processor).
2. All files submitted must be aggregated in one folder with the title: `[UserName]_PG_Bash`, such as `Bhaney44_PG_Bash`.
3. The PR should be titled `[UserName]_Bash`.
4. The program must provide comments using `//` syntax to describe all functions and variables used.
5. All passwords, tokens, and addresses should be removed from the program and indicated with quotations, such as `const red_address = "";`.
6. The pull request for the program must be made before the task Deadline.
7. The program must be run on the Algorand TestNet.
8. Any TestNet Algo or Choice Asset ID may be used in the program.
9. You must provide screenshots or a video link for the program.
10. The program should include a ReadMe file with run steps.
11. As few scripts and files as possible should be used.
12. The program should be written in JavaScript.

Functionality
====================
1. User can create a proposal.
2. User Interface allows for making a customizable proposal.
3. User can call a vote on the proposal through a user interface.
4. Various walls may be implemented, such that a user may need to provide `X`Choice to create a proposal or to call a vote on a proposal.

Additional Information
====================
For more questions or comments, please ask in [Discord](https://discord.gg/33tV4GJA).

**Comment by ChoiceCoin** [comment]
1st prize: Temitopeishola
2nd prize: Samuellyworld
3rd prize: prince-hope1975 | Paella623 | hilary3211
