### ISSUE TITLE
I didn't get my choice coin 

### ISSUE THREAD

**Issue by nosalistic** [ChoiceCoin/Voting#219]
Have done All task, written lovely things about this wonderful project Choice coin here is my wallet ..

TW54YAGZTFRZ6FMGYFFTZ36QC5IT5KZM2AIRHQSBNJFJ6IVE2L3YG7HKGY

**Comment by shadyaftermath** [comment]
I have done the task, written great things about this wonderful project..here is my choice coin wallet

KKYS5QZ3ZYZPLPTSYWGRDKO34WAIFYO2PPEA6F46OU5MMIXMDOF4ZDP6VY

**Comment by excelezy9** [comment]
I have done the task, written great things about this amazing project. Here is my choice coin wallet 

WUWVEKPXXIIEOT3MMSW6GKG45BHZYTUKFJFX3HFE7L3RDD43FL5UWVPQ4M
