### ISSUE TITLE
Choice coin is a big project

### ISSUE THREAD

**Issue by Olufemiomiwole** [ChoiceCoin/Voting#234]
It is spectacular

EPIU72COL6XBCO3Y3Y4UGGYOFBQUZJUM5A7BEOMGDECMMXEJL4HPR7VM34

**Comment by HB2000agba** [comment]
Well this is nice project #Algo
#215 
After I did the fork task 
Did the publish stuff no Choice yet in my wallet
4OQ2LCSPTLUEX2LD2OFEOP7STCA6TNE5RMPB6UHRNL2HFJRW6M3Y4TYN5M
