### ISSUE TITLE
Voting Tutorial Optin Error

### ISSUE THREAD

**Issue by Bhaney44** [ChoiceCoin/Voting#923]
I am working on the [JavaScript Voting Tutorial](https://github.com/ChoiceCoin/Voting/blob/main/Vote_Tutorial/vote_tutorial.js) and I am getting a consistent error.

`An error occured`

`Account '' must opt in to Asset ID 42771692`

The problem is the accounts have already opted into the Asset ID. It looks like the script is catching two errors. First in the voting process:

```
    .catch((error) => {
      if (error.isTtyError) {
        console.log("Cannot render prompt in this environmet");
      } else {
        console.log("An error occured");
      }
    });
```

And once in the results:

```
const checkResultsOne = async () => {
  const address = "";
  const accountInfo = await algodClient.accountInformation(address).do();
  const assets = await accountInfo["assets"];
  for (const asset in assets) {
    if (asset["asset-id"] === ASSET_ID) {
      const amount = asset["amount"];
      console.log(
        `Account ${address} has ${balanceFormatter(amount, ASSET_ID)}`
      );
      return;
    }
  }
  console.log(`Account ${address} must opt in to Asset ID ${ASSET_ID}`);
};
checkResultsOne();
```

The goal is to trouble shoot these errors and fix the problem to run the program smoothly.

**Comment by CRIMSON-CORP** [comment]
I think the value for address should be gotten from checkResultsOne params, as it will always be an empty string everytime checkResultsOne runs... so you might not get desired result for accountInfo and also the assets, therefore you might never find any assest to compare, Hope it helps

**Comment by Bhaney44** [comment]
> I think the value for address should be gotten from checkResultsOne params, as it will always be an empty string everytime checkResultsOne runs... so you might not get desired result for accountInfo and also the assets, therefore you might never find any assest to compare, Hope it helps

Thanks for the reply. I am running the script with an actual address. I just removed it for purposes of posting the issue. I should have mentioned that in the description. Thank you!

**Comment by CRIMSON-CORP** [comment]
Hmm, if that's not the issue, i don't see what is, the script out put is as expected..

Besides, you can declare const amount outside the for in loop, then check if the account has the asset, then run a ternary operator to log the balance, or to log "account must be logged in to ASSET.... "

**Comment by Bhaney44** [comment]
> Hmm, if that's not the issue, i don't see what is, the script out put is as expected..
> 
> Besides, you can declare const amount outside the for in loop, then check if the account has the asset, then run a ternary operator to log the balance, or to log "account must be logged in to ASSET.... "

Right. The function doesn't run on my machine, so the option to vote never appears.

**Comment by prettyirrelevant** [comment]
Hey @Bhaney44 
Sorry about this.

Here's a modified code to fix all issue encountered.
https://pastebin.com/zURWtUA7

Sample screenshot
![image](https://user-images.githubusercontent.com/72208758/144178940-08fbd534-64e9-4b01-b255-bf90f235646f.png)

**Comment by Bhaney44** [comment]
> Hey @Bhaney44 Sorry about this.
> 
> Here's a modified code to fix all issue encountered. https://pastebin.com/zURWtUA7
> 
> Sample screenshot ![image](https://user-images.githubusercontent.com/72208758/144178940-08fbd534-64e9-4b01-b255-bf90f235646f.png)

No need to apologize. I will take a look and let you know how it goes. Thanks for the reply! I don't think this is inherently a opt-in issue either, so I am going to close the issue.

**Comment by Bhaney44** [comment]
> > Hey @Bhaney44 Sorry about this.
> > Here's a modified code to fix all issue encountered. https://pastebin.com/zURWtUA7
> > Sample screenshot ![image](https://user-images.githubusercontent.com/72208758/144178940-08fbd534-64e9-4b01-b255-bf90f235646f.png)
> 
> No need to apologize. I will take a look and let you know how it goes. Thanks for the reply! I don't think this is inherently an opt-in issue either, so I am going to close the issue.

**Comment by LostKlan** [comment]
> I am working on the [JavaScript Voting Tutorial](https://github.com/ChoiceCoin/Voting/blob/main/Vote_Tutorial/vote_tutorial.js) and I am getting a consistent error.
> 
> `An error occured`
> 
> `Account '' must opt in to Asset ID 42771692`
> 
> The problem is the accounts have already opted into the Asset ID. It looks like the script is catching two errors. First in the voting process:
> 
> ```
>     .catch((error) => {
>       if (error.isTtyError) {
>         console.log("Cannot render prompt in this environmet");
>       } else {
>         console.log("An error occured");
>       }
>     });
> ```
> 
> And once in the results:
> 
> ```
> const checkResultsOne = async () => {
>   const address = "";
>   const accountInfo = await algodClient.accountInformation(address).do();
>   const assets = await accountInfo["assets"];
>   for (const asset in assets) {
>     if (asset["asset-id"] === ASSET_ID) {
>       const amount = asset["amount"];
>       console.log(
>         `Account ${address} has ${balanceFormatter(amount, ASSET_ID)}`
>       );
>       return;
>     }
>   }
>   console.log(`Account ${address} must opt in to Asset ID ${ASSET_ID}`);
> };
> checkResultsOne();
> ```
> 
> The goal is to trouble shoot these errors and fix the problem to run the program smoothly.


Try moving the "console.log(`Account ${address} must opt in to Asset ID ${ASSET_ID}`)" into the curly brace directly above it

**Comment by Bhaney44** [comment]
> > I am working on the [JavaScript Voting Tutorial](https://github.com/ChoiceCoin/Voting/blob/main/Vote_Tutorial/vote_tutorial.js) and I am getting a consistent error.
> > `An error occured`
> > `Account '' must opt in to Asset ID 42771692`
> > The problem is the accounts have already opted into the Asset ID. It looks like the script is catching two errors. First in the voting process:
> > ```
> >     .catch((error) => {
> >       if (error.isTtyError) {
> >         console.log("Cannot render prompt in this environmet");
> >       } else {
> >         console.log("An error occured");
> >       }
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And once in the results:
> > ```
> > const checkResultsOne = async () => {
> >   const address = "";
> >   const accountInfo = await algodClient.accountInformation(address).do();
> >   const assets = await accountInfo["assets"];
> >   for (const asset in assets) {
> >     if (asset["asset-id"] === ASSET_ID) {
> >       const amount = asset["amount"];
> >       console.log(
> >         `Account ${address} has ${balanceFormatter(amount, ASSET_ID)}`
> >       );
> >       return;
> >     }
> >   }
> >   console.log(`Account ${address} must opt in to Asset ID ${ASSET_ID}`);
> > };
> > checkResultsOne();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The goal is to trouble shoot these errors and fix the problem to run the program smoothly.
> 
> Try moving the "console.log(`Account ${address} must opt in to Asset ID ${ASSET_ID}`)" into the curly brace directly above it

I actually removed it altogether because it wasn't necessarily indicative of  an opt-in error.

**Comment by LostKlan** [comment]
> > Hey @Bhaney44 Sorry about this.
> > Here's a modified code to fix all issue encountered. https://pastebin.com/zURWtUA7
> > Sample screenshot ![image](https://user-images.githubusercontent.com/72208758/144178940-08fbd534-64e9-4b01-b255-bf90f235646f.png)
> 
> In lines 103 and 104:
> 
> ```
> checkResultsOne();
> checkResultsZero();
> ```
> 
> Are you calling these functions before defining them?

I think javascript allows for such

**Comment by prettyirrelevant** [comment]
> 
> 
> 
> > Hey @Bhaney44 Sorry about this.
> > 
> > Here's a modified code to fix all issue encountered. https://pastebin.com/zURWtUA7
> > 
> > Sample screenshot ![image](https://user-images.githubusercontent.com/72208758/144178940-08fbd534-64e9-4b01-b255-bf90f235646f.png)
> 
> In lines 103 and 104:
> 
> ```
> checkResultsOne();
> checkResultsZero();
> ```
> Are you calling these functions before defining them?
> 

Yes. When functions are defined, the interpreter places them in a global namespace so it can be called lines before it's declaration.
