### ISSUE TITLE
Bronze Bonus Bash

### ISSUE THREAD

**Issue by Bhaney44** [ChoiceCoin/Voting#927]
December 2, 2021 12:49AM PT

**Details**
=============================
**First Prize:** 44,000 Choice | Bronze Badge
**Second Prize:** 27,000 Choice | Bronze Badge
**Deadline:** December 2, 2021 at 11:00AM PT

The Bronze Bonus Bash is open to everyone. This is a 9 hour task to create a function with an `if` statement to send a transaction using the [Algorand JavaScript-SDK](https://github.com/algorand/js-algorand-sdk). To be eligible, the submission must conform to all `Criteria` and `Functionality`. All eligible submissions will be reviewed and two winners will be selected. All participants making eligible pull requests will receive the `Developer` role in the Choice Coin Discord. All questions must be made in the [Choice Coin Discord](https://discord.gg/FDEzT4tZ) in the `#Bronze-Badge` channel or made as a comment to this Issue. The winners will be announced here and on Discord before 5:00 PM PT 12/2/21.

**Criteria**
=============================
1. The program must be a single script executable with the `node` command.
2. The program must be submitted as a [pull request](https://www.youtube.com/watch?v=wosWm1xllLg) in the [Bronze_Badges](https://github.com/ChoiceCoin/Voting/tree/main/Bronze_Badges) folder.
3. The program script should be called `simpleif.js`.
4. The program script should be inside a folder called `if_[user_name]`. For example,` if_bhaney44`.
5. The program must provide comments using `//` syntax to describe all functions and variables used.
6. All passwords, tokens, and addresses should be removed from the program and indicated with quotations, such as `const address_zero = ""; `
7. The pull request for the program must be made before the task Deadline.
8. The program must be run on the Algorand TestNet.
9. A `TXID` must be provided for both outcomes of the `if` statement at the end of the script with comment syntax `//`.
10. Any TestNet Algo or Choice Asset ID may be used in the program. 

**Functionality**
=============================
1. The program must first prompt the user with the text: `Please enter 0 or 1.`
2. The program must define three addresses called: `address_zero`, `address_one`, and `address_two`.
3. The program must define an `if` statement which will be included in a defined function.
4. The `if` statement must determine whether 1 Choice is sent from `address_two` to `address_zero` or `address_one`.
5. Upon the user entry of `0`, the program must send 1 Choice from `address_two` to `address_zero`.
6. Upon the user entry of `1`, the program must send 1 Choice from `address_two` to `address_one`.

*Additional Resources*
=============================
[TestNet Algo Dispenser](https://bank.testnet.algorand.network/)
[Creating a JavaScript Transaction with the PureStake API](https://developer.algorand.org/tutorials/creating-javascript-transaction-purestake-api/)
[PureStake API](https://developer.purestake.io/)
[Choice Coin Python Voting Tutorial](https://github.com/ChoiceCoin/Voting/blob/main/Vote_Tutorial/Vote_Tutorial.py)
[Choice Coin JavaScript Voting Tutorial](https://github.com/ChoiceCoin/Voting/blob/main/Vote_Tutorial/vote_tutorial.js)

**Comment by ChoiceCoin** [comment]
Congrats to the winners! 1st prize @davonjagah 2nd prize @Jaybee020 and @prettyirrelevant 3rd prize @Xekhai and @Oluwatunmise-olat!
