### ISSUE TITLE
Bronze Badge Bash

### ISSUE THREAD

**Issue by ChoiceCoin** [ChoiceCoin/Voting#933]
December 2, 2021 11:30PM

Details
===================

**First Prize:** 44,000.00 Choice
**Second Prize:** 27,000.00 Choice
**Deadline:** December 3, 11:00AM PT

The Bronze Bonus Bash is open to everyone. This is a 9 hour contest. The task is to build a functional frontend integration with the Algorand JavaScript-SDK. All eligible submissions will be reviewed and two winners will be selected. To be eligible for award, all criteria and functionality must be met. The winners will be announced on [Discord](https://discord.com/invite/FDEzT4tZ) before 5:00 PM PT 12/3/21. 

Criteria
======================

1. The program must be submitted as a pull request in the [Bronze_Badges](https://github.com/ChoiceCoin/Voting/tree/main/Bronze_Badges) folder.
2. All files submitted must be aggregated in one folder with the title: `[UserName]_Bash`, such as `Bhaney44_Bash`.
3. The PR should be titled `[UserName]_Bash`.
4. The frontend should be built to this [design](https://github.com/Bhaney44/Voting/blob/main/Bronze_Badges/Sample/SampleTemplate.png).
5. The program must provide comments using `//` syntax to describe all functions and variables used.
6. All passwords, tokens, and addresses should be removed from the program and indicated with quotations, such as `const red_address = "";`.
7. The pull request for the program must be made before the task Deadline.
8. The program must be run on the Algorand TestNet.
9. Any TestNet Algo or Choice Asset ID may be used in the program.

Functionality
======================

1. The program must define three addresses called: `red_address`, `blue_address`, and `button_address`.
2. The program must define an `if` statement which will be included in a defined function.
3. The `if` statement must determine whether 1 Choice is sent from `button_address` to `red_address` or `blue_address`.
4. If `Blue` is selected and the user clicks the `Button`, then the program should send 1 Choice from `button_address` to `blue_address`.
5. If `Red` is selected and the user clicks the `Button`, then the program should send 1 Choice from `button_address` to `red_address`.
6. The `if` statement must activate when the user clicks the `Button`.
7. The user must be able to select either `Red` or `Blue` before clicking the button.

Additional Resources
=====================
[Bash #927](https://github.com/ChoiceCoin/Voting/issues/927).

**Comment by Maxone4u** [comment]
Choice community is fast growing. I'm proud to be part of this.
