### ISSUE TITLE
Refinement Bash/Badge

### ISSUE THREAD

**Issue by Arch222** [ChoiceCoin/Voting#984]
### Details

Work on the **Alpha Vote** folder found in the voting repository.

 Add the option for users to send their preferred amount of Choice, rather than just the constant. IE, the DApp should take in user input and allow them to commit as much Choice as they want for voting.

Add the wallet integration features to the top of the page, instead of it being a separate page. The user should be able to connect to the wallet and vote all within the main page of the application. The user should also be able to see their address at the top of the main page (as with TinyMan). Check out this [repository](https://github.com/barnjamin/algorand-session-wallet) for a simple way to connect all three main wallets (Mobile Wallet, AlgoSigner, and MyAlgoWallet) through a NodeJS Package. 

Add a way for users to know how much Choice they have already committed everything time they connect their wallet. This could be a simple text at the top navbar which tells the user the amount of Choice they have committed to governance. Try using the [AlgoExplorer API](https://algoexplorer.io/api-dev/v2) for this, as you will need to essentially search the transactions for each voting address to find the ones associated with that user. 

Deadline for this challenge is Wednesday, December 16th. You must make a pull request with the title **Refinement Bash** along with your Github Username to be eligible for the reward.  **Winner who successfully accomplishes the challenges above while also delivering the most aesthetically pleasing product will receive 200000 Choice**

**Comment by Bhaney44** [comment]
You must also make sure all of your files are in one folder called `Username_Refine`, the folder should be added as a PR to AlphaVote repository.
